<div class="post">

	<p>
		<img src="/img/about.jpg" alt="Neil Garb" style="float:right;margin:0 0 15px 15px;width:180px;" />
		Hi, my name is Neil Garb and I'm a web developer.  I'm based in Cape Town, South Africa,
		and have been developing in PHP since 2002.
	</p>
	
	<p>
		My posts on this website are a means for me to share my ideas and my inspirations
		with you.  I try not to post tutorials, howtos or step-by-step guides.  Instead I
		try to post about the ideas themselves, hoping they will inspire you to do greater
		things than I am capable of.
	</p>
	
	<p>
		Generally speaking, what inspires me personally is making the amazing out of the
		unlikely.  I think that's why web development is so appealing to me:  the medium of
		the web is relatively so limited, yet people manage to do mind-blowing things with it.
		I hope some of my material inspires you to do the same.
	
	</p>
	
	<h2>Websites I've worked on</h2>
	
	<h3>Codecaine.co.za</h3>

	<p>
		I coded this blog from the ground up using the Zend Framework. I initially tried
		using Wordpress but it frustrated me. I decided it would be quicker and easier to
		just code up my own blogging engine.
	</p>

	<h3><a href="http://www.weylandts.co.za/" title="http://www.weylandts.co.za/" class="external">Weylandts</a></h3>

	<p>
		I built both the new CMS and frontend for weylandts.co.za, using Zend Framework
		1.5. The site involves some interesting extensions of the framework, some of which
		you can read about in my blog.
	</p>

	<p>
		The very pretty design was done by Emma Carpenter, Art Director at OgilvyInteractive
		in Cape Town.
	</p>

	<h3>TravelQuest</h3>

	<p>
		I co-developed Go2Africa.com's CMS, called TravelQuest. I also coded a new version
		of their website, but for reasons beyond my control that version was never published.
		A different frontend went live recently, but it is still powered by TravelQuest. Both
		TravelQuest and my version of the website ran on CakePHP.
	</p>

	<p>
		Co-developed and co-designed with Jonathan 'Airwolf' Abrahams.
	</p>

	<h3><a href="http://www.capetownvillas.net/" title="http://www.capetownvillas.net/" class="external">CapeTownVillas.net</a></h3>

	<p>
		CapeTownVillas.net was the first website I coded to run on TravelQuest. The
		website is powered by CakePHP.
	</p>

	<h3><a href="http://www.ioljobs.co.za/" title="http://www.ioljobs.co.za/" class="external">IOLJobs.co.za</a></h3>
	
	<p>
		IOLjobs.co.za was the last project I completed at Independent Online. This
		project represented the interesting challenge of creating a searchable classified
		ads website for ads which we received in a feed with very little metadata.
	</p>

	<p>
		Designed by Michelle Hayward.
	</p>

	<h3>INMSA's Image Library</h3>

	<p>
		While at Independent Online I had the opportunity to develop the group's
		image library, a system which archived photographs used in production for future
		use. The system allows you to search for photos based on pre-defined IPTC
		information. An interesting challenge in developing this system was to ensure
		that images which were re-used in production did not get re-imported.
	</p>

	<p>
		Designed by Stuart 'stu' Green.	
	</p>	
	
	<h3>And more...</h3>
	
	<ul>
		<li><a href="http://www.vw.co.za/" title="Volkswagen South Africa" class="external">www.vw.co.za</a></li>
		<li><a href="http://www.audi.co.za/" title="Audi of South Africa" class="external">www.audi.co.za</a></li>
		<li><a href="http://www.citilife.co.za/" title="Citi Life" class="external">www.citilife.co.za</a></li>
		<li><a href="http://www.seatsa.co.za/" title="SEAT in South Africa" class="external">www.seatsa.co.za</a></li>
		<li><a href="http://www.iol.co.za/" title="IOL" class="external">www.iol.co.za</a></li>
		<li><a href="http://www.thestar.co.za/" title="The Star" class="external">www.thestar.co.za</a></li>
		<li><a href="http://www.capeargus.co.za/" title="Cape Argus" class="external">www.capeargus.co.za</a></li>
		<li><a href="http://www.motoring.co.za/" title="Motoring.co.za" class="external">www.motoring.co.za</a></li>
		<li><a href="http://www.theloungefactory.co.za/" title="The Lounge Factory" class="external">www.theloungefactory.co.za</a></li>
		<li><a href="http://www.dbass.net/" title="dbass.net" class="external">www.dbass.net</a></li>
	</ul>
	
	<div style="clear:both"></div>

</div>