<div class="post">
	
	<p class="date"><?php echo new Zend_Date($this->post->posted_at, Zend_Date::ISO_8601) ?></p>
	
	<p class="tags">
		Tags:
		<?php foreach ($this->post->findTagViaPostTag() as $tag): ?>
		<a href="/tags/<?php echo $tag->label ?>" title="<?php echo $this->escape($tag->title) ?>"><?php echo $this->escape($tag->title) ?></a> 
		<?php endforeach; ?>	
	</p>
	
	<div class="digg">
		<script src="http://digg.com/tools/diggthis.js" type="text/javascript"></script> 
	</div>

	<?php echo $this->post->body ?>

	<h2>Recent Posts</h2>

	<ul>
		<?php foreach ($this->recentPosts as $post): ?>
		<li><a href="/posts/<?php echo $post->label ?>" title="<?php echo $this->escape($post->title) ?>"><?php echo $this->escape($post->title) ?></a></li>
		<?php endforeach; ?>
	</ul>

</div>

<div id="comments">
	
	<h2>Discussion</h2>
	
	<a href="/posts/<?php echo $this->post->label ?>/rss" title="Discussion on <?php echo $this->escape($this->post->title) ?>" class="rss">Subscribe to an RSS feed of these comments</a>
	
	<?php foreach ($this->comments as $comment): ?>
	<div id="comment-<?php echo $comment->id ?>" class="comment<?php if ($comment->is_super == 1): ?> super<?php endif; ?>">
		<h3>
			<?php if (! empty($comment->website)): ?>
			<a href="<?php echo $comment->website ?>" title="<?php echo $this->escape($comment->name) ?>" class="external"><?php echo $this->escape($comment->name) ?></a>
			<?php else: ?>
			<?php echo $this->escape($comment->name) ?>
			<?php endif; ?>
		</h3>
		<p class="date"><?php echo new Zend_Date($comment->posted_at, Zend_Date::ISO_8601) ?></p>
		<?php echo nl2br(strip_tags($comment->text, '<a>')) ?>
	</div>
	<?php endforeach; ?>

	<div id="form" class="comment">
		<h3>Your comment</h3>
		<?php echo $this->form ?>
	</div>
	
</div>
